apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtlscerts-pkcs12
spec:
  secretName: mtlscerts-pkcs12
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: NAMESPACE.svc
  keystores:
   pkcs12:
     create: true
     passwordSecretRef: 
       name: passphrasesecret
       key: passphrase
  dnsNames:
  - "*.NAMESPACE.svc"
  - spin-x509
  - spin-x509.NAMESPACE.DNS
  - localhost
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  issuerRef:
    name: caissuer
    kind: Issuer
